# https://circleci.com/docs/2.0/language-elixir/
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.3
        environment:
          MIX_ENV: ci
    working_directory: ~/app
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:  # restores saved mix cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile  # get updated dependencies & compile them
      - save_cache:  # generate and store mix cache
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache: # don't forget to save a *build* cache, too
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build

      # specify any bash command here prefixed with `run: `
      - run: mix do deps.get, deps.compile, compile
      - run: mix quality.ci
      - run: mix test
      - store_test_results:  # upload junit test results for display in Test Summary
          # Read more: https://circleci.com/docs/2.0/collect-test-data/
          path: _build/ci/lib/camarero # Replace with the name of your :app
